---
- hosts: routers
  tasks:
    - name: get version information
      cisco.ios.ios_command:
        commands:
          - show version
      vars:
        ansible_persistent_log_messages: True
    - name: fetch logs from remote host
      cisco.ios.ios_command:
        commands:
          - show logging
 
