---
- name: configure cisco routers
  hosts: routers
  connection: ansible.netcommon.network_cli
  gather_facts: yes
  vars: 
    dns: "8.8.8.8 8.8.4.4"
  tasks:
    - name: configure dns
      cisco.ios.ios_config:
        lines: ip name-server {{dns}}
  
