---
- hosts: routers
  tasks: 
    - name: Configure interface settings
      cisco.ios.ios_config:
        lines:
          - network 192.168.143.0 0.0.0.255 area 0      
          - ip address 172.31.1.1 255.255.255.0
        parents: router ospf 10 
        

    - name: Run show ip route  on remote devices
      cisco.ios.ios_command:
        commands:
          - show ip ospf nei

      register: route_output
    - debug: var=route_output.stdout_lines

