---
- hosts: all
  tasks:
  - name: install apache2
    ansible.builtin.package:
      name:
        -  apache2
        - libapache2-mod-php
        - vsftpd
      state: absent
    when: ansible_facts['os_family'] == "debian"

  - name: update nodes
    apt:
      update_cache: yes
      only_upgrade: yes
    when: ansible_distribution == "Ubuntu"
      

  - name: install httpd
    ansible.builtin.package:
      name:
        - httpd
        - vim 
        - php
        - vsftpd
      state: absent
    when: ansible_facts['os_family']  == "RedHat"


  - name: copy file /etc/motd
    copy:
      src: /etc/motd 
      dest: /etc/motd
      mode: 0600
