---
- hosts: routers
  gather_facts: yes
  connection: ansible.netcommon.netowrk_cli
  tasks:
    - name: Run cisco command
      block:
        - name: Run cli
          ansible.netcommon.cli_command:
            command: show ip int br
          register: result

        - name: Cli display
          debug:
            var: result.stdout_lines
          when: ansible_network_os == 'cisco.ios.ios"

